name: shikaku_puzzle
description: A clean offline Flutter Shikaku puzzle game for Android.
publish_to: "none"
version: 1.1.2+4

environment:
  sdk: ^3.12.0

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.5
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/puzzles/
